### ISSUE TITLE
Trouble initializer.StartDate 

### ISSUE THREAD

**Issue by Paul-Mashtakov** [MarketKernel/WebMoney#2]
509Certificate2 x = new X509Certificate2(ConfigurationManager.AppSettings["fileName"]);
var initializer = new Initializer(x);
initializer.StartDate = DateTime.Now.ToUniversalTime();

class Initializer hasn't StartDate  property 

Do I need remove the 3th line from code ?

**Comment by MarketKernel** [comment]
Quite right, there is the error in the documentation. StartDate property was in beta-version and now it is not necessary to set it.

If the default ReqN generation mechanism does not work for you, you can change it as shown in the example https://github.com/MarketKernel/webmoney-business-tools/blob/master/Src/WebMoney.Services/BusinessObjects/AuthenticationSettings/ExtendedInitializer.cs

---------RU----------

Да, здесь ошибка в документации, свойство StartDate было в Beta-версии и сейчас его устанавливать не нужно.

Если вас не устраивает стандартный механизм генерации ReqN, можно его изменить как показано в примере https://github.com/MarketKernel/webmoney-business-tools/blob/master/Src/WebMoney.Services/BusinessObjects/AuthenticationSettings/ExtendedInitializer.cs
